// LOCALHOST

### Get all reviews GET http://localhost:3500/reviews

### Create review POST http://localhost:3500/reviews HTTP/1.1 content-type: application/json

{
"menu_item":"Blue Bombshell w/ Vanilla Cream", "image":"", "review_text":"Probably my favorite Mtn. Dew mix!", "restaurant_name":"Sodalicious", "restaurant_city":"Meridian","restaurant_state":"Idaho", "rating":5, "user":""
}